name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish to LuaRocks
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: luarocks-build-lls-addon
          test_dependencies: |
            luarocks >= 3.11.1
            busted ~> 2.2
            luafilesystem ~> 1.8
            inspect ~> 3.1
            md5 ~> 1.3
          copy_directories: ""

      - name: Get Rockspec Version
        run: |
          [[ "${{ github.ref_name }}" =~ ^v(.+)$ ]]
          echo "spec_version=${BASH_REMATCH[1]}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "luarocks-build-lls-addon-${spec_version}.src.rock"
