name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.4.8"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Publish to LuaRocks
        run: |
          luarocks upload \
            rockspec/luarocks-build-lls-addon-${{ github.ref_name }}.rockspec \
            --api-key=${{ secrets.LUAROCKS_API_KEY }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.src.rock"
